set_property( GLOBAL PROPERTY CHIK       ${CMAKE_CURRENT_LIST_DIR} )
set_property( GLOBAL PROPERTY LIBCHIK    ${CMAKE_CURRENT_LIST_DIR}/../libchik )
set_property( GLOBAL PROPERTY CHIK_GAMES ${CMAKE_CURRENT_LIST_DIR}/../games )